version: '3.8'

services:
  register-app:
    build: ./
    restart: always
    container_name: register-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/reload/dist
    depends_on:
      - kafka
    command: npm run dev --workspace=services/register

  inventory-app:
    build: ./
    restart: always
    container_name: inventory-service
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/reload/dist
    depends_on:
      - kafka
    command: npm run dev --workspace=services/inventory

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka

volumes:
  kafka_data: